# ARRAY

In [2]:
import numpy
arr = [float(i) for i in input("enter the input numbers : ").strip().split()]
arr.reverse()
print(numpy.array(arr,float))

enter the input numbers : 1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# shape reshape

In [7]:
arr = [int(i) for i in input("enter the input numbers : ").strip().split()]
N_array=numpy.array(arr)
print(N_array.shape)
print("reshaped : ")
print(numpy.reshape(N_array,(3,3)))

enter the input numbers : 1 2 3 4 5 6 7 8 9
(9,)
reshaped : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# transpose and flatten

In [10]:
import numpy
n,m = map(int,input("enter dimensions : ").split())
mat = numpy.array([[int(x) for x in input("enter number row wise : ").split()] for k in range(n)])
print("Transpose : \n {}".format(numpy.transpose(mat)))
print(mat.flatten())

enter dimensions2 2
enter number row wise : 1 2
enter number row wise : 3 4
Transpose : 
 [[1 3]
 [2 4]]
[1 2 3 4]


# concatenate

Input Format

The first line contains space separated integers N,M and P .
The next N lines contains the space separated elements of the P columns.
After that, the next M lines contains the space separated elements of the P columns.

Print the concatenated array of size (N+M) X (P)

In [17]:
n,m,p= map(int,input("enter dimensions : ").split())
arr1=[[int(i) for i in input("Enter numbers : ").split()] for k in range(n)]
print(numpy.array(arr1))

enter dimensions : 4 3 2
Enter numbers : 1 2
Enter numbers : 1 2
Enter numbers : 1 2
Enter numbers : 1 2
[[1 2]
 [1 2]
 [1 2]
 [1 2]]


In [18]:
arr2=[[int(i) for i in input(f"Enter {p} numbers : ").split()] for k in range(m)]
print(numpy.array(arr2))

Enter 2 numbers : 3 4
Enter 2 numbers : 3 4
Enter 2 numbers : 3 4
[[3 4]
 [3 4]
 [3 4]]


In [19]:
numpy.concatenate([arr1, arr2], axis = 0) # adding row wise

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

# zeros and ones

In [24]:
N = [int(x) for x in input("enter - elements *rows*cols : ").split()]
print(numpy.zeros(N, dtype = numpy.int))
print(numpy.ones(N, dtype = numpy.int))

enter - elements *rows*cols : 3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Eye and identity

In [27]:
n,m= map(int,input("enter dimensions row*cols : ").split())
print(numpy.identity(n))
print(numpy.eye(n,m))

enter dimensions row*cols : 3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# array maths

In [28]:
n,m=map(int,input("Array size :").split())
A=numpy.array([list(map(int,input("elements of A").split())) for i in range(n)])
B=numpy.array([list(map(int,input("elements of B").split())) for i in range(n)])
print(A+B,A-B,A*B,A//B,A%B,A**B,sep='\n')

Array size :1 4
elements of A1 2 3 4
elements of B5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# floor ceil rint

In [29]:
A=numpy.array(list(map(float,input("enter numbers : ").split())))
print(numpy.floor(A),numpy.ceil(A),numpy.rint(A),sep='\n')

enter numbers : 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


#  sum and prod


In [30]:
r,c= map(int,input("enter dimensions : ").split())
arr1=[[int(i) for i in input("Enter numbers : ").split()] for k in range(r)]
print(numpy.array(arr1))

enter dimensions : 2 2
Enter numbers : 1 2
Enter numbers : 3 4
[[1 2]
 [3 4]]


In [32]:
print(numpy.sum(arr1,axis=0))
print(numpy.product(arr1))
print(numpy.sum(arr1,axis=1))

[4 6]
24
[3 7]


# MIN and Max

In [33]:
r,c= map(int,input("enter dimensions : ").split())
arr1=[[int(i) for i in input("Enter numbers : ").split()] for k in range(r)]
print(numpy.array(arr1))

enter dimensions : 4 2
Enter numbers : 2 5 
Enter numbers : 3 7
Enter numbers : 1 3
Enter numbers : 4 0
[[2 5]
 [3 7]
 [1 3]
 [4 0]]


In [36]:
print(numpy.min(arr1, axis = 0) )       
print(numpy.min(arr1, axis = 1))
print(numpy.max(arr1, axis = 0) )        
print(numpy.max(arr1, axis = 1))

[1 0]
[2 3 1 0]
[4 7]
[5 7 3 4]


# mean var std

In [37]:
r,c= map(int,input("enter dimensions : ").split())
arr1=[[int(i) for i in input("Enter numbers : ").split()] for k in range(r)]
print(numpy.array(arr1))

enter dimensions : 2 2
Enter numbers : 1 2
Enter numbers : 3 4
[[1 2]
 [3 4]]


In [38]:
print(numpy.mean(arr1, axis = 1))
print(numpy.var(arr1, axis = 0))
print(numpy.std(arr1))

[1.5 3.5]
[1. 1.]
1.118033988749895


# dot and cross

In [40]:
n=int(input("enter dimensions : "))
arr1=[[int(i) for i in input("Enter numbers : ").split()] for k in range(r)]
print(numpy.array(arr1))

enter dimensions : 2
Enter numbers : 1 2
Enter numbers : 3 4
[[1 2]
 [3 4]]


In [41]:
n=int(input("enter dimensions : "))
arr2=[[int(i) for i in input("Enter numbers : ").split()] for k in range(r)]
print(numpy.array(arr2))

enter dimensions : 2
Enter numbers : 1 2
Enter numbers : 3 4
[[1 2]
 [3 4]]


In [42]:
print(numpy.cross(arr1,arr2))
print(numpy.dot(arr1,arr2))

[0 0]
[[ 7 10]
 [15 22]]


# inner and outer

In [44]:
arr1=[[int(i) for i in input("Enter numbers : ").split()] ]
arr2=[[int(i) for i in input("Enter numbers : ").split()] ]
print(numpy.inner(arr1, arr2))
print(numpy.outer(arr1, arr2))


Enter numbers : 0 1
Enter numbers : 2 3
[[3]]
[[0 0]
 [2 3]]


# polynomials

In [45]:
coefs=list(map(float,input("values : ").split()))
x=float(input("x point : "))

print(numpy.polyval(coefs,x))

values : 1.1 2 3
x point : 0
3.0


# linear algebra

In [47]:
n=int(input("enter dimensions : "))
arr2=[[float(i) for i in input("Enter numbers : ").split()] for k in range(r)]
print(numpy.array(arr2))

enter dimensions : 2
Enter numbers : 1.1 1.1
Enter numbers : 1.1 1.1
[[1.1 1.1]
 [1.1 1.1]]


In [48]:
#find determinant
print(numpy.linalg.det(arr2))

0.0
